@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Apr 06 16:40:33 -0600 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto f2498544386a47578a2a25891f31c629 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Smiley_Face_tb_behav xil_defaultlib.Smiley_Face_tb -log elaborate.log"
call xelab  -wto f2498544386a47578a2a25891f31c629 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Smiley_Face_tb_behav xil_defaultlib.Smiley_Face_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
