set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports Count]
set_property IOSTANDARD LVCMOS33 [get_ports Sum]
set_property PACKAGE_PIN J15 [get_ports A]
set_property PACKAGE_PIN L16 [get_ports B]
set_property PACKAGE_PIN H17 [get_ports Count]
set_property PACKAGE_PIN K15 [get_ports Sum]
