set_property SRC_FILE_INFO {cfile:C:/Users/kbastola1/Desktop/FrequencyDivider/FrequencyDivider.srcs/constrs_1/new/FrequencyDivider_constrain.xdc rfile:../../../FrequencyDivider.srcs/constrs_1/new/FrequencyDivider_constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports Clock_1Hz]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports Clock_System]
