set_property SRC_FILE_INFO {cfile:C:/Users/kbastola1/Desktop/Gray_Code_Counter/Gray_Code_Counter.srcs/constrs_1/new/Gray_Code_counter_constrain.xdc rfile:../../../Gray_Code_Counter.srcs/constrs_1/new/Gray_Code_counter_constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {Count[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {Count[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports Clock_System]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports Reset]
